apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "users-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/users/db/host
      name: DB_HOST
    - key: {{ .Release.Namespace }}/users/db/user
      name: DB_USER
    - key: {{ .Release.Namespace }}/users/db/pass
      name: DB_PASSWORD
    - key: {{ .Release.Namespace }}/users/email/user
      name: EMAIL_USERNAME
    - key: {{ .Release.Namespace }}/users/email/password
      name: EMAIL_PASSWORD
    - key: {{ .Release.Namespace }}/users/email/host
      name: EMAIL_HOST
    - key: {{ .Release.Namespace }}/users/cio/site_id
      name: CIO_SITE_ID
    - key: {{ .Release.Namespace }}/users/cio/api_key
      name: CIO_API_KEY
