apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "users-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/users/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/users/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/users/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/user
    secretKey: EMAIL_USERNAME
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/password
    secretKey: EMAIL_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/host
    secretKey: EMAIL_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/metatx/ethereum/rpc_url
    secretKey: MAIN_RPC_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/users/cio/api_key
    secretKey: CUSTOMER_IO_API_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "users-api.fullname" . }}-secret
    template:
      metadata: {}
