PORT: 3000
LOG_LEVEL: info
DB_USER: dimo
DB_PASSWORD: dimo
DB_PORT: 5432
DB_HOST: localhost
DB_NAME: users_api
DB_MAX_OPEN_CONNECTIONS: 5
DB_MAX_IDLE_CONNECTIONS: 5
SERVICE_NAME: users-api
EMAIL_HOST: localhost
EMAIL_PORT: 1025
EMAIL_USERNAME: dimo
EMAIL_PASSWORD: dimo
EMAIL_FROM: mailer@dimo.zone
