apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "devices-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/devices/db/host
      name: DB_HOST
    - key: {{ .Release.Namespace }}/devices/db/user
      name: DB_USER
    - key: {{ .Release.Namespace }}/devices/db/pass
      name: DB_PASSWORD