apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devices-api.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devices-api.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}