replicaCount: 2
image:
  repository: dimozone/users-api
  pullPolicy: IfNotPresent
  tag: 0.2.0
env:
  PORT: '8080'
  LOG_LEVEL: info
  DB_PORT: '5432'
  DB_NAME: users_api
  DB_MAX_OPEN_CONNECTIONS: '10'
  DB_MAX_IDLE_CONNECTIONS: '3'
  EMAIL_PORT: 587
  SERVICE_NAME: users-api
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  EMAIL_FROM: hello@dimo.zone
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '9'
    external-dns.alpha.kubernetes.io/hostname: users-api.dimo.zone
  hosts:
    - host: users-api.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
