name: buildpush
on:
  push:
    tags:
      - v*

jobs:
  build_test:
    # The type of runner that the job will run on
    name: buildpush
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./resources/docker/Dockerfile
          push: true
          tags: dimozone/users-api:${{steps.tag.outputs.tag}}

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@v0.14.0
        with:
          valueFile: 'charts/users-api/values-prod.yaml'
          propertyPath: 'image.tag'
          value: ${{steps.tag.outputs.tag}}
          branch: main
          message: 'Update Image Version to ${{steps.tag.outputs.tag}}'