name: gotest

on:
  pull_request:
    branches: [ '**' ]

jobs:
  tests:
        # Condition to skip merge commits
    if: "!contains(github.event.head_commit.message, 'Merge pull request')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Get dependencies
        run: |
          go get -v -t ./...
          go install gotest.tools/gotestsum@latest

      - name: modVerify
        run: go mod verify

      - name: modTidy
        run: go mod tidy

      - name: Run Tests with go testsum
        run: gotestsum --format pkgname --jsonfile test.json

      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test.json
